package com.prosegur.rulesEngine.services.soapClient.WsRespostaCalculo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-09-10T10:57:17.652+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "WsRespostaCalculoSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WsRespostaCalculoSoap {

    @WebResult(name = "ComunicaPeticionFinalizadaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ComunicaPeticionFinalizada", targetNamespace = "http://tempuri.org/", className = "com.prosegur.rulesEngine.services.soapClient.WsRespostaCalculo.ComunicaPeticionFinalizada")
    @WebMethod(operationName = "ComunicaPeticionFinalizada", action = "http://tempuri.org/ComunicaPeticionFinalizada")
    @ResponseWrapper(localName = "ComunicaPeticionFinalizadaResponse", targetNamespace = "http://tempuri.org/", className = "com.prosegur.rulesEngine.services.soapClient.WsRespostaCalculo.ComunicaPeticionFinalizadaResponse")
    public com.prosegur.rulesEngine.services.soapClient.WsRespostaCalculo.PeticionFinalizadaResponse comunicaPeticionFinalizada(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.prosegur.rulesEngine.services.soapClient.WsRespostaCalculo.PeticionFinalizadaRequest request
    );
}
